apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-api
  template:
    metadata:
      labels:
        app: java-api
    spec:
      containers:
        - name: java-api
          image: josephmj0303/emart-java-api:3a05034
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/emart
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: rootpass
          readinessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
